version: "3"

services:
  app:
    image: openjdk:17-jdk-slim-bullseye
    tty: true
    environment:
      DatabaseJDBC: "jdbc:mysql://db:3306/agapeapp?user=admin&password=mypassword&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      ConnectionStrings__Storage: "http://minio:minio123@minio:9000"
      ConnectionStrings__Cache: "redis"
    volumes:
      - "..:/home/AgapeApp" # Asegúrate de que el directorio montado corresponda a la estructura de tu proyecto Java
    ports:
      - "8080:8080" # Asegúrate de que el puerto concuerde con el configurado en tu aplicación Spring Boot
    depends_on:
      - db
  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
  redis:
    image: redis
  db: 
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "agapeapp"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_ROOT_PASSWORD: "mypassword"
    ports:
      - 3306:3306